const WEBHOOK_URL='https://n8n-3ceafyuyasrd.litium.sumopod.my.id/webhook/bfaa35ad-1766-46c1-8376-cbd7d66e4a79';
function logoSVG(size=48){return `<svg class="logo-svg" width="${size}" height="${size}" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><circle cx="32" cy="20" r="3.5" fill="#6fb44a"/><path d="M32 20V32" stroke="#6fb44a" stroke-width="3" stroke-linecap="round"/><circle cx="68" cy="20" r="3.5" fill="#69c0ec"/><path d="M68 20V32" stroke="#69c0ec" stroke-width="3" stroke-linecap="round"/><path d="M50 28H36C27.1634 28 20 35.1634 20 44V60C20 68.8366 27.1634 76 36 76H50V28Z" fill="#f7fbf3" stroke="#6fb44a" stroke-width="3.5" stroke-linejoin="round"/><path d="M50 28H64C72.8366 28 80 35.1634 80 44V60C80 68.8366 72.8366 76 64 76H50V28Z" fill="#f4faff" stroke="#69c0ec" stroke-width="3.5" stroke-linejoin="round"/><rect x="15" y="46" width="5" height="12" rx="2.5" fill="#6fb44a"/><rect x="80" y="46" width="5" height="12" rx="2.5" fill="#69c0ec"/><rect x="28" y="43" width="44" height="16" rx="8" fill="#1e293b"/><circle cx="40" cy="51" r="3.5" fill="#86efac"/><circle cx="60" cy="51" r="3.5" fill="#7dd3fc"/><path d="M44 76H56V80C56 81.1046 55.1046 82 54 82H46C44.8954 82 44 81.1046 44 80V76Z" fill="#e2e8f0" stroke="#94a3b8" stroke-width="2"/></svg>`}
document.querySelectorAll('.logo-wrap').forEach(el=>{const size=Number(el.dataset.logo||48);el.innerHTML=logoSVG(size)+(el.dataset.text==='false'?'':'<span class="logo-wordmark"><span class="eco">ECO</span><span class="tech">TECH</span></span>')});
if(window.lucide) lucide.createIcons();
const navbar=document.getElementById('navbar');
window.addEventListener('scroll',()=>navbar.classList.toggle('scrolled',window.scrollY>30));
const toggle=document.getElementById('menuToggle'), menu=document.getElementById('mobileMenu');
toggle?.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.innerHTML=`<i data-lucide="${open?'x':'menu'}"></i>`;lucide.createIcons()});
menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<i data-lucide="menu"></i>';lucide.createIcons()}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();
const form=document.getElementById('contactForm'), error=document.getElementById('formError'), success=document.getElementById('formSuccess'), submit=document.getElementById('submitButton'), sendAnother=document.getElementById('sendAnother');
form?.addEventListener('submit',async e=>{e.preventDefault();error.classList.add('hidden');submit.disabled=true;submit.innerHTML='<i data-lucide="loader-circle"></i><span>Mengirim Pesan...</span>';lucide.createIcons();const payload={name:document.getElementById('name').value,email:document.getElementById('email').value,message:document.getElementById('message').value,timestamp:new Date().toISOString(),source:'ECOTECH Landing Page'};try{const res=await fetch(WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('Webhook error');form.reset();form.classList.add('hidden');success.classList.remove('hidden');}catch(err){console.error(err);error.classList.remove('hidden')}finally{submit.disabled=false;submit.innerHTML='<i data-lucide="send"></i><span>Kirim Pesan Email</span>';lucide.createIcons()}});
sendAnother?.addEventListener('click',()=>{success.classList.add('hidden');form.classList.remove('hidden');document.getElementById('name').focus()});
